# Generated by Django 6.0.7 on 2026-07-22 17:11

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('website_url', models.URLField(verbose_name='website URL')),
                ('scan_enabled', models.BooleanField(default=True, verbose_name='scan enabled')),
                ('last_scanned_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last scanned at')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_company_name')],
            },
        ),
    ]
