# Generated by Django 6.0.7 on 2026-07-22 19:06

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('normalized_name', models.CharField(max_length=255, verbose_name='normalized name')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('normalized_name'), name='unique_normalized_name_name')],
            },
        ),
    ]
