# Generated by Django 6.0.7 on 2026-07-27 15:20

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('normalized_name', models.CharField(editable=False, max_length=255, verbose_name='normalized name')),
                ('identity_key', models.CharField(default='', editable=False, max_length=255, verbose_name='identity key')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'indexes': [models.Index(django.db.models.functions.text.Lower('normalized_name'), name='person_normalized_idx'), models.Index(fields=['identity_key'], name='person_identity_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('identity_key'), django.db.models.functions.text.Lower('middle_name'), name='unique_person_identity')],
            },
        ),
        migrations.CreateModel(
            name='PersonMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('mention_type', models.PositiveSmallIntegerField(choices=[(0, 'profile'), (1, 'organizational unit'), (2, 'other')], default=2, verbose_name='mention type')),
                ('role_title', models.CharField(max_length=512, verbose_name='role title')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='phone number')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mentions', to='persons.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'person mention',
                'verbose_name_plural': 'persons mentions',
            },
        ),
    ]
