# Generated by Django 6.0.7 on 2026-07-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('scans', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmention',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_mentions', to='scans.scan', verbose_name='scan'),
        ),
        migrations.AddField(
            model_name='personmention',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_mentions', to='sources.source', verbose_name='source'),
        ),
        migrations.AddIndex(
            model_name='personmention',
            index=models.Index(fields=['person', 'created_timestamp'], name='mention_person_created_idx'),
        ),
        migrations.AddIndex(
            model_name='personmention',
            index=models.Index(fields=['scan', 'person'], name='mention_scan_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='personmention',
            constraint=models.UniqueConstraint(fields=('scan', 'person', 'source'), name='unique_person_source_mention_per_scan'),
        ),
    ]
