# Generated by Django 6.0.7 on 2026-07-23 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('mention_type', models.PositiveSmallIntegerField(choices=[(0, 'profile'), (1, 'team'), (2, 'author'), (3, 'interview'), (4, 'quote'), (5, 'event'), (6, 'other')], default=6, verbose_name='mention type')),
                ('context', models.TextField(verbose_name='context')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mentions', to='persons.person', verbose_name='person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_mentions', to='sources.source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'person mention',
                'verbose_name_plural': 'persons mentions',
                'constraints': [models.UniqueConstraint(fields=('person', 'source'), name='unique_person_source_mention')],
            },
        ),
    ]
