# Generated by Django 6.0.7 on 2026-07-22 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'running'), (2, 'completed'), (3, 'failed')], default=0, verbose_name='scan status')),
                ('pages_scanned', models.PositiveIntegerField(default=0, verbose_name='pages scanned')),
                ('report', models.TextField(blank=True, default='', verbose_name='report')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', (0, 1))), fields=('company',), name='unique_active_scan_per_company')],
            },
        ),
    ]
