# Generated by Django 6.0.7 on 2026-07-24 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('persons', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'running'), (2, 'completed'), (3, 'failed')], default=0, verbose_name='scan status')),
                ('pages_scanned', models.PositiveIntegerField(default=0, verbose_name='pages scanned')),
                ('report', models.TextField(blank=True, default='', verbose_name='report')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'scan',
                'verbose_name_plural': 'scans',
            },
        ),
        migrations.CreateModel(
            name='PersonSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('position_type', models.PositiveSmallIntegerField(choices=[(0, 'partner'), (1, 'director'), (2, 'other')], default=2, verbose_name='position type')),
                ('role_title', models.CharField(max_length=255, verbose_name='role title')),
                ('organizational_unit', models.CharField(blank=True, default='', max_length=255, verbose_name='organizational unit')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='phone number')),
                ('confirmation_level', models.PositiveSmallIntegerField(choices=[(0, 'confirmed'), (1, 'high'), (2, 'low')], default=2, verbose_name='confirmation level')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='persons.person', verbose_name='person')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_snapshots', to='sources.source', verbose_name='source')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_snapshots', to='scans.scan', verbose_name='scan')),
            ],
            options={
                'verbose_name': 'person snapshot',
                'verbose_name_plural': 'person snapshots',
            },
        ),
        migrations.CreateModel(
            name='ScanSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='scans.scan', verbose_name='scan')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_links', to='sources.source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'scan source',
                'verbose_name_plural': 'scan sources',
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['company', 'created_timestamp'], name='scan_company_created_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status', 'created_timestamp'], name='scan_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='scan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', (0, 1))), fields=('company',), name='unique_active_scan_per_company'),
        ),
        migrations.AddIndex(
            model_name='personsnapshot',
            index=models.Index(fields=['scan', 'created_timestamp'], name='snapshot_scan_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='personsnapshot',
            constraint=models.UniqueConstraint(fields=('scan', 'person', 'role_title', 'organizational_unit'), name='unique_person_snapshot_role_per_scan'),
        ),
        migrations.AddConstraint(
            model_name='scansource',
            constraint=models.UniqueConstraint(fields=('scan', 'source'), name='unique_source_per_scan'),
        ),
    ]
