# Generated by Django 6.0.7 on 2026-07-23 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('url', models.URLField(verbose_name='url')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('page_type', models.PositiveSmallIntegerField(choices=[(0, 'profile'), (1, 'team'), (2, 'publication'), (3, 'interview'), (4, 'news'), (5, 'event'), (6, 'document'), (7, 'other')], default=7, verbose_name='page type')),
                ('published_timestamp', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published at')),
                ('content', models.TextField(verbose_name='content')),
                ('content_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='content hash')),
            ],
            options={
                'verbose_name': 'source',
                'verbose_name_plural': 'sources',
                'indexes': [models.Index(fields=['url'], name='source_url_idx'), models.Index(fields=['page_type', 'created_timestamp'], name='source_page_type_created_idx')],
            },
        ),
    ]
